#!/bin/bash

ST=$1
END=$((ST + 19))

for (( IDX=ST+1; IDX<=END; IDX++ ))
do
echo "${IDX} in ${ST} to ${END}"
# ./CW_1S2S_Arr_test --opts_fn Submission_Scripts/1S2S_Spectra_Arr/Options_Files/Oct_x_test.txt --part_group_idx 0 --part_member_idx ${IDX}
done

for (( IDX=ST; IDX<=END; IDX++ ))
do 
./CW_1S2S --opts_fn Submission_Scripts/CW_1S2S_Spectrum_Cooled/Options_Files/Spec_Det/Oct_x_0.txt --part_group_idx 0 --part_member_idx ${IDX}
done
